### PR TITLE
Add Django 1.8 migrations

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by czpython** [comment]
I'm not a fan of setting the south migrations to blank, instead I'd just move the existing migrations into south_migrations and add the django 1.7 ones to migrations

**Comment by astagi** [comment]
hi @czpython yeah that's what I did :) I didn't add any blank migrations, I just moved existing ones to the south_migrations folder but in git diff you just see a new add of 0001_initial but it's not mine.

**Comment by czpython** [comment]
ahh yes you're right. :+1:

**Comment by astagi** [comment]
:smile: thanks!

**Pull request merged**
